# This is a basic workflow to help you get started with Actions

name: first wfl

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  # This workflow contains a single job called "build"
  firstjob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: print hi
        run : echo "hi"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello, world!"

   
